version: '3'

services:

  mysql:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: angigaram
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: docker.for.mac.localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      ANGIGARAM_SLACK_BOT_OAUTH_TOKEN: ${ANGIGARAM_SLACK_BOT_OAUTH_TOKEN}
      ANGIGARAM_SUPPORTED_BADGES: ${ANGIGARAM_SUPPORTED_BADGES}
      ANGIGARAM_TOTAL_DAILY_BADGES: ${ANGIGARAM_TOTAL_DAILY_BADGES}
